name: Generate

on:
  schedule:
    - cron: "0 */3 * * *"

  workflow_dispatch: {}

jobs:
  generate:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v3
      - name: Install node
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: ${{ inputs.node-version }}
      - run: ./generate.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
